service: smart-compose-ai
frameworkVersion: '4'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs20.x
  stage: 'dev'
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - '*'
          Resource: '*'

functions:
  api:
    handler: api-get.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  createCustomer:
    handler: api-post.handler
    events:
      - http:
          path: /smart-compose-ai
          method: post
          cors: true

