service: smart-compose-ai
frameworkVersion: '4'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs20.x
  stage: 'dev'
  environment:
    OPENAI_API_URL: ${env:OPENAI_API_URL, 'xxxx'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, 'xxxx'}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - '*'
          Resource: '*'

functions:
  get:
    handler: src/api/get.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  post:
    handler: src/api/post.handler
    events:
      - http:
          path: /smart-compose-ai
          method: post
          cors: true

